apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.label.app }}
  labels:
    app: {{ .Values.label.app }}
    tier: {{ .Values.label.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.label.app }}
      tier: {{ .Values.label.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.label.app }}
        tier: {{ .Values.label.app }}
    spec:
      containers:
      - name: {{ .Values.label.app }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: http_proxy
          value: 127.0.0.1:30101
      - name: {{ .Values.label.name }}
        image: thanda/mesher:osi
        env:
        - name: CSE_REGISTRY_ADDR
          value : http://servicecenter:30100
        - name: SERVICE_NAME
          value: {{ .Values.label.app }}
        - name: VERSION
          value: 0.0.1
        - name: APP_ID
          value: OSIConference
        ports:
        - containerPort: 80
